name: Generation Pacman Animation

on:
   schedule:
      - cron: "* */12 * * *"  
   workflow_dispatch:
   push: 
       branches:
       - main

   jobs:
      generate:
        permissions:
          contents:
      runs-on: unbuntu-latest
      timeout-minutes: 5

      steps:
        - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with: 
        github_user_name: ${{github.repository_owner}}

        - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        whit: 
        target_branch: output
